### ISSUE TITLE
Rust supports wasm32-unknown-unknown target now

### ISSUE THREAD

**Issue by bennyyip** [dtysky/wasm-usage-guide#1]
See https://github.com/rust-lang/rust/pull/45905 and https://www.hellorust.com/setup/wasm-target/.
FYI, https://github.com/alexcrichton/wasm-gc may reduce the output size.

**Comment by dtysky** [comment]
Thanks for your suggestion, but after trying:  

```bash
wasm-gc src/rust-es/test.wasm src/rust-es/test1.wasm
```
I found the size of wasm file did not change a bit.

I think the reason of a huge size of output wasm file and js file is: **rustc** does not pass any options to **emcc**, so **emcc** will generate codes with default options (include all runtime code).

**Comment by dtysky** [comment]
Sorry...it looks I misunderstand what you say.
I will add the usage of wasm-unknown-unknown to this guide tomorrow.

Thanks.
